# Generated by Django 4.1.3 on 2022-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyRepsponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.CharField(max_length=50)),
                ("user_id", models.IntegerField()),
                ("timestamp", models.DateField()),
                ("family", models.BooleanField()),
                ("partner", models.BooleanField()),
                ("friends", models.BooleanField()),
                ("colleagues", models.BooleanField()),
                ("weather", models.IntegerField()),
                ("sleep", models.FloatField()),
                ("work", models.FloatField()),
                ("sports", models.IntegerField()),
                ("hobbies", models.IntegerField()),
                ("social", models.IntegerField()),
                ("health", models.IntegerField()),
                ("mood", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_ID", models.IntegerField()),
                ("user_name", models.CharField(max_length=50)),
                ("user_password", models.CharField(max_length=50)),
            ],
        ),
    ]
