# Generated by Django 4.1.3 on 2022-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="surveyrepsponse", name="body",),
        migrations.AlterField(
            model_name="surveyrepsponse",
            name="colleagues",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyrepsponse",
            name="family",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyrepsponse",
            name="friends",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyrepsponse",
            name="partner",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyrepsponse",
            name="timestamp",
            field=models.DateField(auto_now=True),
        ),
    ]
